addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
matrix:
  fast_finish: true
script:
  - npm run test:coverage
after_success:
  - npm i -g coveralls@latest
  - cat ./coverage/lcov.info | coveralls
